### ISSUE TITLE
Prep for releasing v2.2.0

### ISSUE THREAD

**Issue by KeeperOfMaps** [CosmoQuestX/Rocket-Bot#14]
Hey @TheRealFakeAdmin, could you clean up the README.md and related files in `nightly` in anticipation of releasing v.2.2.0, please? Thanks!

**Comment by TheRealFakeAdmin** [comment]
@KeeperOfMaps I'll start work on the CHANGELOG. Anything I particularly need to change about the README (other than the Details section)?

**Comment by KeeperOfMaps** [comment]
Just have a look through things and remove anything specific to nightly. I can create a branch for the v2.2.0 release if that would help so you can keep nightly-specific things in there.

Also, I would be most appreciative if you could look at the metar.js in the other branch and see if you can get it to send the raw_data to the channel. I'm not worried about the other fields right now. I think I'm one step away from succeeding at that, but it'll be easier if you could do it. :)

**Comment by TheRealFakeAdmin** [comment]
Yeah, could you make a branch; Something like `nightly-merge`?

I'll check out the `metar.js` when I get to it. Knowing me, it'll probably be before I start the `CHANGELOG` (so soon).

**Comment by KeeperOfMaps** [comment]
Done!
