### ISSUE TITLE
Random image command

### ISSUE THREAD

**Issue by KeeperOfMaps** [CosmoQuestX/Rocket-Bot#20]
I made a typo when issuing the !ping command and @starstryder commented ["I now want png to be a random image"](https://discord.com/channels/443490369443856384/1002737022529708113/1013137611138801834).

After some discussion, it was decided that maybe the random image could be a random APOD.

**Comment by TheRealFakeAdmin** [comment]
### NASA's APOD Open API Options
- save a list of all the APODs (if there is no size limit) using `start_date` & `end_date` then select a random query every call
- generate a random date (formatted `YYYY-MM-DD`) using `date`

### The NASA Open API APOD docs
![image](https://user-images.githubusercontent.com/22807122/187055368-413a2978-af7d-4b7b-9e28-c74195ea5134.png)

*NASA Open API Docs & Info from [here](https://api.nasa.gov/#browseAPI)*

**Comment by KeeperOfMaps** [comment]
Easier: generate a random date since APOD a started and serve that. Means no need to retrieve and store all of the APODs since it's unlikely to be used at a high rate.
