### ISSUE TITLE
Bot responds to @here

### ISSUE THREAD

**Issue by KeeperOfMaps** [CosmoQuestX/Rocket-Bot#23]
@here & presumably @everyone mentions the bot, and there is no check for those, so it responds.

It shouldn't.

**Comment by TheRealFakeAdmin** [comment]
@KeeperOfMaps After some searching, i found that this was an issue in `v2.1` but has since been fixed in `v2.2`. The bot on the server is currently running `v2.1`.

 *Could you add the label `wontfix` & close this issue for me?*
